config/routes.rb
Rails.application.routes.draw do
  root to: "zeikins#index"
  resources :zeikins, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/zeikins_controller.rb
class ZeikinsController < ApplicationController

  def index
    
  end

  def show
    case params[:id] 
      when "1"
        render "show_1"
      when "2"
        render 'show_2'
      when "3"
        render 'show_3'
      when "11"
        render 'show_11'
      when "12"
        render 'show_12'
      when "13"
        render 'show_13'
      when "21"
        render 'show_21'
      when "22"
        render 'show_22'
      when "23"
        render 'show_23'
      when "31"
        render 'show_31'
      when "32"
        render 'show_32'
      when "33"
        render 'show_33'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zeikins_helper.rb
module ZeikinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>税金Checker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" crossorigin="anonymous" />
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>
    <%= yield %>
  </body>
</html>

app/views/zeikins/_footer.html.erb
<style> 


</style>

<div class="footer-container">
  <footer class="footer">
    <div class="md-flex md-justify-between">
      <a href="#" class="footer__logo">
        税金CHECKER
      </a>
      <ul class="footer__navi flex">
        <li><a href="#">About</a></li>
        <li><a href="#">サイトマップ</a></li>
        <li><a href="#">プライバシーポリシー</a></li>
      </ul>
    </div>
  <hr />
    <p class="copyright">
      © 2023 <a href="#">税金CHECKER Inc.</a> All Rights Reserved.
    </p>
  </footer>
</div>

app/views/zeikins/_form.html.erb
<script>
  function convertToHalfWidth(input) {
   // 全角文字を半角文字に変換
    const halfWidthText = input.value.replace(/[０-９Ａ-Ｚａ-ｚ]/g, function(s) {
    return String.fromCharCode(s.charCodeAt(0) - 0xFEE0);
  });

    // 半角文字以外の文字を削除
    const alphanumericText = halfWidthText.replace(/[^a-zA-Z0-9]/g, '');

    // 入力フィールドにセット
    input.value = alphanumericText;
}
</script>

<div class="forms">
  <div class="basic-salary">
    <label for="basicSalary">基本月給 (円):</label>
    <input type="text" id="basicSalary" name="basicSalary" class="right-align" rrequired autocomplete="off">
  </div>
  <%# 就業地 %>
  <div class="countoly">
    <label for="workLocation">就業地:</label>
    <select id="workLocation" name="workLocation">
      <option value="">都道府県を選択</option>
      <option value="北海道">北海道</option>
      <option value="青森県">青森県</option>
      <option value="岩手県">岩手県</option>
      <option value="宮城県">宮城県</option>
      <option value="秋田県">秋田県</option>
      <option value="山形県">山形県</option>
      <option value="福島県">福島県</option>
      <option value="茨城県">茨城県</option>
      <option value="栃木県">栃木県</option>
      <option value="群馬県">群馬県</option>
      <option value="埼玉県">埼玉県</option>
      <option value="千葉県">千葉県</option>
      <option value="東京都">東京都</option>
      <option value="神奈川県">神奈川県</option>
      <option value="新潟県">新潟県</option>
      <option value="富山県">富山県</option>
      <option value="石川県">石川県</option>
      <option value="福井県">福井県</option>
      <option value="山梨県">山梨県</option>
      <option value="長野県">長野県</option>
      <option value="岐阜県">岐阜県</option>
      <option value="静岡県">静岡県</option>
      <option value="愛知県">愛知県</option>
      <option value="三重県">三重県</option>
      <option value="滋賀県">滋賀県</option>
      <option value="京都府">京都府</option>
      <option value="大阪府">大阪府</option>
      <option value="兵庫県">兵庫県</option>
      <option value="奈良県">奈良県</option>
      <option value="和歌山県">和歌山県</option>
      <option value="鳥取県">鳥取県</option>
      <option value="島根県">島根県</option>
      <option value="岡山県">岡山県</option>
      <option value="広島県">広島県</option>
      <option value="山口県">山口県</option>
      <option value="徳島県">徳島県</option>
      <option value="香川県">香川県</option>
      <option value="愛媛県">愛媛県</option>
      <option value="高知県">高知県</option>
      <option value="福岡県">福岡県</option>
      <option value="佐賀県">佐賀県</option>
      <option value="長崎県">長崎県</option>
      <option value="熊本県">熊本県</option>
      <option value="大分県">大分県</option>
      <option value="宮崎県">宮崎県</option>
      <option value="鹿児島県">鹿児島県</option>
      <option value="沖縄県">沖縄県</option>
    </select>
  </div>
  <%# 年齢 %>
  <div class="age">
    <label for="age">年齢 (歳):</label>
  <div class="icon-selector">
    <select id="age" name="age">
      <option value=""><i class="fas fa-baby">---</i></option>
      <option value="10"><i class="fas fa-baby">10</i></option>
      <option value="20"><i class="fas fa-child">20</i></option>
      <option value="30"><i class="fas fa-user">30</i></option>
      <option value="40"><i class="fas fa-user-tie">40</i></option>
      <option value="50"><i class="fas fa-user-graduate">50</i></option>
      <option value="60"><i class="fas fa-user-secret">60</i></option>
      <option value="70"><i class="fas fa-user-astronaut">70</i></option>
      <!-- 他のアイコンと値のオプションを追加 -->
    </select>
  </div>
</div>
    <%# 扶養人数 %>
    <div class="num">
  <label for="dependents">扶養人数:</label>
  <div class="icon-selector">
    <select id="dependents" name="dependents">
    <option value="0"><i class="fas fa-user">0人</i></option>
      <option value="1"><i class="fas fa-user">1人</i></option>
      <option value="2"><i class="fas fa-users">2人</i></option>
      <option value="3"><i class="fas fa-users">3人</i></option>
      <option value="4"><i class="fas fa-users">4人</i></option>
      <option value="5"><i class="fas fa-users">5人</i></option>
      <option value="6"><i class="fas fa-users">6人</i></option>
      <option value="7"><i class="fas fa-users">7人</i></option>
      <option value="8"><i class="fas fa-users">8人</i></option>
      <option value="9"><i class="fas fa-users">9人</i></option>
      <option value="10"><i class="fas fa-users">10人</i></option>
      <!-- 他のアイコンと値のオプションを追加 -->
    </select>
  </div>
</div>
    <%# 残業代 %>
    <div class="overtime-pay">
      <label for="overtimePay">残業代 (円):</label>
      <input type="text" id="overtimePay" name="overtimePay" class="right-align" required autocomplete="off">
    </div>
    <%# 交通費 %>
    <div class="transportation-cost">
      <label for="transportationCost">交通費 (円):</label>
      <input type="text" id="transportationCost" name="transportationCost" class="right-align" required autocomplete="off">
    </div>
    <%# 計算 %>
    <div class= "keisan">
      <button type="button" id="send-button" onclick="calculateSalary(); showResults();">計算</button>
    </div>
    </form>
  </div>
</div>

app/views/zeikins/_header.html.erb
<body>
  <script>
    // Add your existing JavaScript code here
    document.addEventListener('turbo:load', function() {
      var navLists = document.querySelector('.nav-lists');
      document.body.classList.add('loaded');
      navLists.classList.add('visible');
    });

    function toggleMenu() {
      var navLists = document.querySelector('.nav-lists');
      navLists.classList.toggle('visible');
    }

    function toggleNewMenu() {
    var newNavLists = document.querySelector('.new-nav-lists');
    newNavLists.classList.toggle('visible');
}
  </script>

  <header>
    <div class="hedder">
      <div class="kk">
        <div class="heading">
          <h1 class="title">
            <span>税</span>
            <span>金</span>
            <span>&nbsp;</span>
            <span>C</span>
            <span>H</span>
            <span>E</span>
            <span>C</span>
            <span>K</span>
            <span>E</span>
            <span>R</span>
          </h1>
        </div>
      </div>
       <div class="new-hamburger-btn" onclick="toggleNewMenu()">
        <div class="bar"></div>
        <div class="bar"></div>
        <div class="bar"></div>
      </div>

      <!-- 新しいメニュー -->
      <ul class="new-nav-lists">
        <li class="lists"><a href="#" class="list">ホーム</a></li>
        <li class="lists"><a href="#" class="list">使い方</a></li>
        <li class="lists"><a href="#" class="list">用語集</a></li>
      </ul>
      <div class="navbar">
        <ul class="nav-lists">
          <li class="lists"><a href="#" class="list">ホーム</a></li>
          <li class="lists"><a href="#" class="list">使い方</a></li>
          <li class="lists"><a href="#" class="list">用語集</a></li>
        </ul>
      </div>

     
    </div>
  </header>
</body>
</html>

app/views/zeikins/_icon.html.erb
<script>
const lastHoveredIcon = null;

function toggleListOnHover(listId) {
  const list = document.getElementById(listId);

  if (lastHoveredIcon === listId && list.style.display !== 'none') {
    // カーソルが同じアイコンまたは文字に戻ってきたら何もしない
    return;
  }

  hideAllLists();
  list.style.display = 'block';
  lastHoveredIcon = listId;
}

function hideAllLists() {
  const allLists = document.querySelectorAll('.icon-lists ul');
  allLists.forEach(function(item) {
    item.style.display = 'none';
  });
}
</script>

<div class="icons">
  <div class="icon-container" >
    <%= image_tag("pig.png", class: "icon-logo") %>
    <h2 class="genre">年金</h2>
    <div class="icon-lists">
      <ul id="list1">
        <li><%= link_to '老齢基礎年金', zeikin_path(1) %></li>
      </ul>
    </div>
  </div>


  <div class="icon-container" >
    <%= image_tag("coin.png", class: "icon-logo") %>
    <h2 class="genre">所得税</h2>
    <div class="icon-lists">
    <div class="lis">
      <ul id="list2" >
        <li><%= link_to '詳細1', zeikin_path(11) %></li>
      </ul>
      </div>
    </div>
  </div>

  <div class="icon-container" >
    <%= image_tag("clinical.png", class: "icon-logo") %>
    <h2 class="genre">医療・保険</h2>
    <div class="icon-lists">
      <ul id="list3" >
        <li><%= link_to '詳細1', zeikin_path(21) %></li>
      </ul>
    </div>
  </div>

  <div class="icon-container" >
    <%= image_tag("house.png", class: "icon-logo") %>
    <h2 class="genre">住宅</h2>
    <div class="icon-lists">
      <ul id="list4" >
        <li><%= link_to '詳細1', zeikin_path(31) %></li>
      </ul>
    </div>
  </div>
</div>

app/views/zeikins/_result.html.erb
<div class ="result" id="result">
  <table id="salaryResultTable">
    <thead>
      <tr>
        <th>項目</th>
        <th>金額 (円)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>基本月給</td>
        <td id="basicSalaryAmount">0円</td>
      </tr>
      <tr>
        <td>厚生年金</td>
        <td id="pensionAmount">0円</td>
      </tr>
      <tr>
        <td>健康保険</td>
        <td id="healthInsuranceAmount">0円</td>
      </tr>
      <tr>
        <td>雇用保険</td>
        <td id="employmentInsuranceAmount">0円</td>
      </tr>
      <tr>
        <td>国民年金</td>
        <td id="nationalPensionAmount">0円</td>
      </tr>
      <tr>
        <td>国民健康保険</td>
        <td id="nationalHealthInsuranceAmount">0円</td>
      </tr>
      <tr>
        <td>所得税</td>
        <td id="incomeTaxAmount">0円</td>
      </tr>
      <tr>
        <td>住民税</td>
        <td id="residentTaxAmount">0円</td>
      </tr>
      <tr>
        <td>手取り収入</td>
        <td id="netIncome">0円</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/zeikins/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Salary Simulation</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<style>
  ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  a {
    color: #999;
    text-decoration: none;
  }

  a:hover {
    color: #000;
  }

  .flex {
    display: flex;
  }

  hr {
    height: 1px;
    border: 0;
    border-top: 1px solid #e5e7eb;
  }

  .footer {
    padding: 2rem;
    font-size: 15px;
    color: #999;
    background: #fff;
    margin-top:500px;
  }

  .footer__navi {
    flex-wrap: wrap;
    margin-bottom: 2rem;
  }

  .footer__navi li {
    display: inline-block;
  }

  .footer__navi li:not(:last-child) {
    margin-right: 16px;
  }

  .footer__logo {
    display: inline-block;
    margin-bottom: 1rem;
  }


@media(max-width: 1024px) {
  .footer{
    height:50px;
    margin-top:calc(10% + 50px);
  }

  .md-flex {
    display: flex;
  }

  .md-justify-between {
    justify-content: space-between;
  }

  .copyright {
    text-align: left;
  }
}

@media (max-width: 700px) {
  /* フッター */
  .footer{
    height: 80px; /* 適切な高さに調整する */
    margin-top: calc(10% + 80px);
  }
}
</style>
<body>
      <%# ヘッダー %>
      <%= render partial: "header" %>
  <div class="bg">
    <div class="main">
      <div class="m">
      <%# 円グラフ %>
      <div class= "graph">
        <canvas id="myDonutChart" width="300" height="300"></canvas>
      </div>
      <%# 入力フォーム %>
      <div class="format">
      <%= render partial:"form"%>
      </div>
      <%# 上までがフォーマット %>
      <div class="z">
        <p class="shu">シミュレーション</p>
      </div>
      <%# 結果 %>
      <%= render partial: "result" %>
      <%# アイコン %>
      <div>
        <%= render partial: "icon"%>
      </div>
      <%# フッター %>
      <div class="under">
        <%= render partial: "footer"%>
      </div>
</div>

app/views/zeikins/show_1.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Salary Simulation</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
  
<style>
  .format .right-align {
    text-align: right;
  }
  .format{
    height:400px;
  }
</style>


<body>

<script>
  function calculatePension() {
    let workYears = parseInt(document.getElementById('workYears').value, 10);
    let unemployedMonths = parseInt(document.getElementById('unemployedMonths').value, 10);
    let additionalMonths = parseInt(document.getElementById('additionalMonths').value, 10);

    function convertToHalfWidth(value) {
      return value.replace(/[0-9]/g, function (s) {
      return String.fromCharCode(s.charCodeAt(0) - 0xFEE0);
      });
    }
      // 必要な条件分岐を追加
      if (isNaN(workYears) || isNaN(unemployedMonths) || isNaN(additionalMonths)) {
          alert("入力が不足しています。全ての項目を入力勤続年数は半角で入力してくださいしてください。");
      return;
          }
      // 勤めた年と雇用されていなかった月、追納した月の回数を合算して納付済み月数を計算
    let paidMonths = workYears * 12 - unemployedMonths + additionalMonths;
    let pensionAmountTotal = Math.floor(777800 * (paidMonths / 480));
    let pensionAmountMonthly = Math.floor(pensionAmountTotal / 12);

        document.getElementById('Amount_1_monthly').textContent = pensionAmountMonthly.toLocaleString() + '円';
        document.getElementById('Amount_1_total').textContent = pensionAmountTotal.toLocaleString() + '円'; 
          updateDonutChart(pensionAmountTotal);
      }

    function updateDonutChart(pensionAmount) {
      let ctx = document.getElementById('myDonutChart_1').getContext('2d');
      let myDonutChart = new Chart(ctx, {
          type: 'doughnut',
          data: {
            datasets: [{
              data: [pensionAmount, 0],
              backgroundColor: ['#36A2EB', '#FFFFFF'],
            }],
          },
            options: {
              cutoutPercentage: 70,
              responsive: true,
            },
        });
      }
</script>

<%# ヘッダー %>
<%= render partial: "header" %>
<div class="bg">
  <div class="main">
    <div class="m">
    <%# 円グラフ %>
    <div class= "graph">
      <canvas id="myDonutChart_1" width="300" height="300"></canvas>
    </div>
    <%# 入力フォーム %>
    <div class="format">
      <div class="form-container">
        <label for="workYears">勤続年数:</label>
          <select id="workYears"  required>
            <option value="">選択してください</option>
            <option value="0">0年</option>
            <option value="1">1年</option>
            <option value="2">2年</option>
            <option value="3">3年</option>
            <option value="4">4年</option>
            <option value="5">5年</option>
            <option value="6">6年</option>
            <option value="7">7年</option>
            <option value="8">8年</option>
            <option value="9">9年</option>
            <option value="10">10年</option>
            <option value="11">11年</option>
            <option value="12">12年</option>
            <option value="13">13年</option>
            <option value="14">14年</option>
            <option value="15">15年</option>
            <option value="16">16年</option>
            <option value="17">17年</option>
            <option value="18">18年</option>
            <option value="19">19年</option>
            <option value="20">20年</option>
            <option value="21">21年</option>
            <option value="22">22年</option>
            <option value="23">23年</option>
            <option value="24">24年</option>
            <option value="25">25年</option>
            <option value="26">26年</option>
            <option value="27">27年</option>
            <option value="28">28年</option>
            <option value="29">29年</option>
            <option value="30">30年</option>
            <option value="31">31年</option>
            <option value="32">32年</option>
            <option value="33">33年</option>
            <option value="34">34年</option>
            <option value="35">35年</option>
            <option value="36">36年</option>
            <option value="37">37年</option>
            <option value="38">38年</option>
            <option value="39">39年</option>
            <option value="40">40年</option>
            </select>
      </div>
      <div class="form-container">
        <label for="unemployedMonths">雇用されていなかった月:</label>
          <select id="unemployedMonths"  required>
          <option value="">選択してください</option>
          <option value="0">0ヶ月</option>
          <option value="1">1ヶ月</option>
          <option value="2">2ヶ月</option>
          <option value="3">3ヶ月</option>
          <option value="4">4ヶ月</option>
          <option value="5">5ヶ月</option>
          <option value="6">6ヶ月</option>
          <option value="8">8ヶ月</option>
          <option value="9">9ヶ月</option>
          <option value="10">10ヶ月</option>
          <option value="11">11ヶ月</option>
          <option value="12">12ヶ月</option>
          </select>
      </div>
      <div class="form-container">
        <label for="additionalMonths">追納した月の回数:</label>
          <select id="additionalMonths" required>
          <option value="">選択してください</option>
          <option value="0">0ヶ月</option>
          <option value="1">1ヶ月</option>
          <option value="2">2ヶ月</option>
          <option value="3">3ヶ月</option>
          <option value="4">4ヶ月</option>
          <option value="5">5ヶ月</option>
          <option value="6">6ヶ月</option>
          <option value="7">7ヶ月</option>
          <option value="8">8ヶ月</option>
          <option value="9">9ヶ月</option>
          <option value="10">10ヶ月</option>
          <option value="11">11ヶ月</option>
          <option value="12">12ヶ月</option>
          </select>
      </div>
      <%# 計算 %>
      <div class= "keisan">
        <button type="button" id="result" onclick="calculatePension(); showResults_1();">計算</button>
      </div>
      </form>
      </div>
      </div>
      <%# 上までがフォーマット %>
      <div class="z">
        <p class="shu">シミュレーション</p>
      </div>
      <%# 結果 %>
      <div class ="result" id="result">
        <table id="salaryResultTable">
          <thead>
            <tr>
            <th>項目</th>
            <th>金額 (円)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            <td>老齢基礎年金（年間総支給額）</td>
            <td id="Amount_1_total">0円</td>
            </tr>
            <tr>
            <td>老齢基礎年金（月間支給額）</td>
            <td id="Amount_1_monthly">0円</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div>
      <%= render partial: "icon"%>
      </div>
      <%# フッター %>
      <div class="under">
        <%= render partial: "footer"%>
      </div>
</div>

app/views/zeikins/show_11.html.erb
11

app/views/zeikins/show_21.html.erb
21

app/views/zeikins/show_31.html.erb
31